eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9769/eureka/ #注册中心地址
  instance:
    prefer-ip-address: true #使用ip地址注册
    instance-id: zuul-server:9772  #指定服务的id
server:
  port: 9772
zuul:
  ignored-services: "*"   #禁止使用服务名字进行访问
  prefix: "/servers"  #统一的前缀
  routes: #配置路由，指定服务的访问路径
    resource1-server: "/resources/**"
spring:
  application:
    name: zuul-server